# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Que\Desktop\Programming\Python\Projects\Music_Downloader\View\DownloaderUI.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(803, 605)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget_main = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget_main.setEnabled(True)
        self.tabWidget_main.setGeometry(QtCore.QRect(0, 0, 801, 551))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        self.tabWidget_main.setFont(font)
        self.tabWidget_main.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget_main.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget_main.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget_main.setObjectName("tabWidget_main")
        self.tab_youtubeDownloader = QtWidgets.QWidget()
        self.tab_youtubeDownloader.setObjectName("tab_youtubeDownloader")
        self.gridLayoutWidget = QtWidgets.QWidget(self.tab_youtubeDownloader)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 791, 511))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.btn_youtubeChannel_addRemove = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        self.btn_youtubeChannel_addRemove.setFont(font)
        self.btn_youtubeChannel_addRemove.setObjectName("btn_youtubeChannel_addRemove")
        self.gridLayout.addWidget(self.btn_youtubeChannel_addRemove, 3, 4, 1, 1)
        self.btn_youtubeChannel_updateList = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        self.btn_youtubeChannel_updateList.setFont(font)
        self.btn_youtubeChannel_updateList.setObjectName("btn_youtubeChannel_updateList")
        self.gridLayout.addWidget(self.btn_youtubeChannel_updateList, 3, 2, 1, 1)
        self.btn_youtubeChannel_download = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        self.btn_youtubeChannel_download.setFont(font)
        self.btn_youtubeChannel_download.setObjectName("btn_youtubeChannel_download")
        self.gridLayout.addWidget(self.btn_youtubeChannel_download, 3, 6, 1, 1)
        self.listWidget_youtubeChannel = QtWidgets.QListWidget(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        self.listWidget_youtubeChannel.setFont(font)
        self.listWidget_youtubeChannel.setObjectName("listWidget_youtubeChannel")
        self.gridLayout.addWidget(self.listWidget_youtubeChannel, 0, 0, 1, 8)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 3, 1, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout.addLayout(self.verticalLayout_2, 3, 0, 1, 1)
        self.btn_youtubeChannel_removeFromList = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_youtubeChannel_removeFromList.setObjectName("btn_youtubeChannel_removeFromList")
        self.gridLayout.addWidget(self.btn_youtubeChannel_removeFromList, 3, 3, 1, 1)
        self.tabWidget_main.addTab(self.tab_youtubeDownloader, "")
        self.tab_musicDownloader = QtWidgets.QWidget()
        self.tab_musicDownloader.setObjectName("tab_musicDownloader")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.tab_musicDownloader)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 791, 511))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lbl_musicDl_listWidgetInfo = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_musicDl_listWidgetInfo.setFont(font)
        self.lbl_musicDl_listWidgetInfo.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_musicDl_listWidgetInfo.setObjectName("lbl_musicDl_listWidgetInfo")
        self.gridLayout_2.addWidget(self.lbl_musicDl_listWidgetInfo, 2, 3, 1, 1)
        self.btn_musicDl_downloadAlbums = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        self.btn_musicDl_downloadAlbums.setFont(font)
        self.btn_musicDl_downloadAlbums.setObjectName("btn_musicDl_downloadAlbums")
        self.gridLayout_2.addWidget(self.btn_musicDl_downloadAlbums, 2, 5, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 2, 2, 1, 1)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.lbl_musicDl_artistNameInfo = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_musicDl_artistNameInfo.setFont(font)
        self.lbl_musicDl_artistNameInfo.setObjectName("lbl_musicDl_artistNameInfo")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lbl_musicDl_artistNameInfo)
        self.lineEdit_musicDl_spotifyArtistName = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_musicDl_spotifyArtistName.setObjectName("lineEdit_musicDl_spotifyArtistName")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_musicDl_spotifyArtistName)
        self.lbl_musicDl_artistIdInfo = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_musicDl_artistIdInfo.setFont(font)
        self.lbl_musicDl_artistIdInfo.setObjectName("lbl_musicDl_artistIdInfo")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.lbl_musicDl_artistIdInfo)
        self.lineEdit_musicDl_spotifyArtistId = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        self.lineEdit_musicDl_spotifyArtistId.setFont(font)
        self.lineEdit_musicDl_spotifyArtistId.setObjectName("lineEdit_musicDl_spotifyArtistId")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_musicDl_spotifyArtistId)
        self.comboBox_musicDl_artistInDB = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_musicDl_artistInDB.sizePolicy().hasHeightForWidth())
        self.comboBox_musicDl_artistInDB.setSizePolicy(sizePolicy)
        self.comboBox_musicDl_artistInDB.setMaxVisibleItems(10)
        self.comboBox_musicDl_artistInDB.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.comboBox_musicDl_artistInDB.setObjectName("comboBox_musicDl_artistInDB")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.comboBox_musicDl_artistInDB)
        self.lbl_musicDl_artistComboBoxInfo = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_musicDl_artistComboBoxInfo.setFont(font)
        self.lbl_musicDl_artistComboBoxInfo.setObjectName("lbl_musicDl_artistComboBoxInfo")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.lbl_musicDl_artistComboBoxInfo)
        self.checkBox_musicDl_enableComboBox = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.checkBox_musicDl_enableComboBox.setObjectName("checkBox_musicDl_enableComboBox")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.checkBox_musicDl_enableComboBox)
        self.lbl_musicDl_enableComboBox = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lbl_musicDl_enableComboBox.setFont(font)
        self.lbl_musicDl_enableComboBox.setObjectName("lbl_musicDl_enableComboBox")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.lbl_musicDl_enableComboBox)
        self.gridLayout_2.addLayout(self.formLayout, 0, 1, 1, 5)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 2, 4, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 0, 0, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_musicDl_populateLists = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        self.btn_musicDl_populateLists.setFont(font)
        self.btn_musicDl_populateLists.setObjectName("btn_musicDl_populateLists")
        self.verticalLayout.addWidget(self.btn_musicDl_populateLists)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.btn_musicDl_toDownload = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        self.btn_musicDl_toDownload.setFont(font)
        self.btn_musicDl_toDownload.setObjectName("btn_musicDl_toDownload")
        self.verticalLayout.addWidget(self.btn_musicDl_toDownload)
        self.lbl_musicDL_transferInfo = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(12)
        self.lbl_musicDL_transferInfo.setFont(font)
        self.lbl_musicDL_transferInfo.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_musicDL_transferInfo.setObjectName("lbl_musicDL_transferInfo")
        self.verticalLayout.addWidget(self.lbl_musicDL_transferInfo)
        self.btn_musicDl_toFound = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        self.btn_musicDl_toFound.setFont(font)
        self.btn_musicDl_toFound.setObjectName("btn_musicDl_toFound")
        self.verticalLayout.addWidget(self.btn_musicDl_toFound)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem5)
        self.btn_musicDl_lookupAlbum = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        self.btn_musicDl_lookupAlbum.setFont(font)
        self.btn_musicDl_lookupAlbum.setObjectName("btn_musicDl_lookupAlbum")
        self.verticalLayout.addWidget(self.btn_musicDl_lookupAlbum)
        self.gridLayout_3.addLayout(self.verticalLayout, 1, 1, 1, 1)
        self.listWidget_musicDl_albumsFound = QtWidgets.QListWidget(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        self.listWidget_musicDl_albumsFound.setFont(font)
        self.listWidget_musicDl_albumsFound.setObjectName("listWidget_musicDl_albumsFound")
        self.gridLayout_3.addWidget(self.listWidget_musicDl_albumsFound, 1, 0, 1, 1)
        self.listWidget_musicDl_albumsDownload = QtWidgets.QListWidget(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        self.listWidget_musicDl_albumsDownload.setFont(font)
        self.listWidget_musicDl_albumsDownload.setObjectName("listWidget_musicDl_albumsDownload")
        self.gridLayout_3.addWidget(self.listWidget_musicDl_albumsDownload, 1, 2, 1, 1)
        self.lbl_musicDl_albumsFound = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(12)
        self.lbl_musicDl_albumsFound.setFont(font)
        self.lbl_musicDl_albumsFound.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_musicDl_albumsFound.setObjectName("lbl_musicDl_albumsFound")
        self.gridLayout_3.addWidget(self.lbl_musicDl_albumsFound, 0, 0, 1, 1)
        self.lbl_musicDl_albumsToDownload = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(12)
        font.setItalic(False)
        font.setUnderline(False)
        self.lbl_musicDl_albumsToDownload.setFont(font)
        self.lbl_musicDl_albumsToDownload.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_musicDl_albumsToDownload.setObjectName("lbl_musicDl_albumsToDownload")
        self.gridLayout_3.addWidget(self.lbl_musicDl_albumsToDownload, 0, 2, 1, 1)
        self.lbl_musicDl_downloaded = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lbl_musicDl_downloaded.setFont(font)
        self.lbl_musicDl_downloaded.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_musicDl_downloaded.setObjectName("lbl_musicDl_downloaded")
        self.gridLayout_3.addWidget(self.lbl_musicDl_downloaded, 0, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_3, 1, 0, 1, 6)
        self.tabWidget_main.addTab(self.tab_musicDownloader, "")
        self.tab_album_correction = QtWidgets.QWidget()
        self.tab_album_correction.setObjectName("tab_album_correction")
        self.gridLayoutWidget_7 = QtWidgets.QWidget(self.tab_album_correction)
        self.gridLayoutWidget_7.setGeometry(QtCore.QRect(0, 0, 791, 511))
        self.gridLayoutWidget_7.setObjectName("gridLayoutWidget_7")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.gridLayoutWidget_7)
        self.gridLayout_15.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.btn_albumCorrection_updateSong = QtWidgets.QPushButton(self.gridLayoutWidget_7)
        self.btn_albumCorrection_updateSong.setObjectName("btn_albumCorrection_updateSong")
        self.gridLayout_15.addWidget(self.btn_albumCorrection_updateSong, 1, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_15.addItem(spacerItem6, 1, 0, 1, 1)
        self.gridLayout_16 = QtWidgets.QGridLayout()
        self.gridLayout_16.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.lbl_albumCorrection_song_spotify_id = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.lbl_albumCorrection_song_spotify_id.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_albumCorrection_song_spotify_id.setObjectName("lbl_albumCorrection_song_spotify_id")
        self.gridLayout_16.addWidget(self.lbl_albumCorrection_song_spotify_id, 11, 0, 1, 1)
        self.lbl_albumCorrection_songYoutubeId = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.lbl_albumCorrection_songYoutubeId.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_albumCorrection_songYoutubeId.setObjectName("lbl_albumCorrection_songYoutubeId")
        self.gridLayout_16.addWidget(self.lbl_albumCorrection_songYoutubeId, 9, 1, 1, 1)
        self.gridLayout_17 = QtWidgets.QGridLayout()
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.lbl_albumCorrection_songLbl = QtWidgets.QLabel(self.gridLayoutWidget_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_albumCorrection_songLbl.sizePolicy().hasHeightForWidth())
        self.lbl_albumCorrection_songLbl.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_albumCorrection_songLbl.setFont(font)
        self.lbl_albumCorrection_songLbl.setObjectName("lbl_albumCorrection_songLbl")
        self.gridLayout_17.addWidget(self.lbl_albumCorrection_songLbl, 2, 0, 1, 1)
        self.lbl_albumCorrection_albumLbl = QtWidgets.QLabel(self.gridLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_albumCorrection_albumLbl.setFont(font)
        self.lbl_albumCorrection_albumLbl.setObjectName("lbl_albumCorrection_albumLbl")
        self.gridLayout_17.addWidget(self.lbl_albumCorrection_albumLbl, 1, 0, 1, 1)
        self.comboBox_albumCorrection_album = QtWidgets.QComboBox(self.gridLayoutWidget_7)
        self.comboBox_albumCorrection_album.setObjectName("comboBox_albumCorrection_album")
        self.gridLayout_17.addWidget(self.comboBox_albumCorrection_album, 1, 1, 1, 1)
        self.comboBox_albumCorrection_song = QtWidgets.QComboBox(self.gridLayoutWidget_7)
        self.comboBox_albumCorrection_song.setObjectName("comboBox_albumCorrection_song")
        self.gridLayout_17.addWidget(self.comboBox_albumCorrection_song, 2, 1, 1, 1)
        self.lbl_albumCorrection_artistLbl = QtWidgets.QLabel(self.gridLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_albumCorrection_artistLbl.setFont(font)
        self.lbl_albumCorrection_artistLbl.setObjectName("lbl_albumCorrection_artistLbl")
        self.gridLayout_17.addWidget(self.lbl_albumCorrection_artistLbl, 0, 0, 1, 1)
        self.comboBox_albumCorrection_artist = QtWidgets.QComboBox(self.gridLayoutWidget_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_albumCorrection_artist.sizePolicy().hasHeightForWidth())
        self.comboBox_albumCorrection_artist.setSizePolicy(sizePolicy)
        self.comboBox_albumCorrection_artist.setObjectName("comboBox_albumCorrection_artist")
        self.gridLayout_17.addWidget(self.comboBox_albumCorrection_artist, 0, 1, 1, 1)
        self.gridLayout_16.addLayout(self.gridLayout_17, 7, 0, 1, 2)
        self.lineEdit_albumCorrection_song_youtube_id = QtWidgets.QLineEdit(self.gridLayoutWidget_7)
        self.lineEdit_albumCorrection_song_youtube_id.setObjectName("lineEdit_albumCorrection_song_youtube_id")
        self.gridLayout_16.addWidget(self.lineEdit_albumCorrection_song_youtube_id, 10, 1, 1, 1)
        self.lbl_albumCorrection_song_name = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.lbl_albumCorrection_song_name.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_albumCorrection_song_name.setObjectName("lbl_albumCorrection_song_name")
        self.gridLayout_16.addWidget(self.lbl_albumCorrection_song_name, 9, 0, 1, 1)
        self.lineEdit_albumCorrection_song_spotify_Id = QtWidgets.QLineEdit(self.gridLayoutWidget_7)
        self.lineEdit_albumCorrection_song_spotify_Id.setObjectName("lineEdit_albumCorrection_song_spotify_Id")
        self.gridLayout_16.addWidget(self.lineEdit_albumCorrection_song_spotify_Id, 12, 0, 1, 1)
        self.lineEdit_albumCorrection_song_name = QtWidgets.QLineEdit(self.gridLayoutWidget_7)
        self.lineEdit_albumCorrection_song_name.setObjectName("lineEdit_albumCorrection_song_name")
        self.gridLayout_16.addWidget(self.lineEdit_albumCorrection_song_name, 10, 0, 1, 1)
        self.gridLayout_19 = QtWidgets.QGridLayout()
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.lbl_AlbumCorrection_completionText = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.lbl_AlbumCorrection_completionText.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_AlbumCorrection_completionText.setObjectName("lbl_AlbumCorrection_completionText")
        self.gridLayout_19.addWidget(self.lbl_AlbumCorrection_completionText, 0, 1, 1, 1)
        self.gridLayout_16.addLayout(self.gridLayout_19, 11, 1, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_16.addItem(spacerItem7, 14, 0, 1, 1)
        self.btn_albumCorrection_youtubeWebSearch = QtWidgets.QPushButton(self.gridLayoutWidget_7)
        self.btn_albumCorrection_youtubeWebSearch.setObjectName("btn_albumCorrection_youtubeWebSearch")
        self.gridLayout_16.addWidget(self.btn_albumCorrection_youtubeWebSearch, 12, 1, 1, 1)
        self.gridLayout_15.addLayout(self.gridLayout_16, 0, 0, 1, 2)
        self.tabWidget_main.addTab(self.tab_album_correction, "")
        self.tab_Settings = QtWidgets.QWidget()
        self.tab_Settings.setObjectName("tab_Settings")
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.tab_Settings)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(0, 0, 791, 511))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.lbl_settings_apiInfo = QtWidgets.QLabel(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_settings_apiInfo.setFont(font)
        self.lbl_settings_apiInfo.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_settings_apiInfo.setObjectName("lbl_settings_apiInfo")
        self.gridLayout_7.addWidget(self.lbl_settings_apiInfo, 0, 0, 1, 1)
        self.gridLayout_13 = QtWidgets.QGridLayout()
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.lbl_settings_youtubeConfirmation = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.lbl_settings_youtubeConfirmation.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_settings_youtubeConfirmation.setObjectName("lbl_settings_youtubeConfirmation")
        self.gridLayout_13.addWidget(self.lbl_settings_youtubeConfirmation, 2, 3, 1, 1)
        self.lbl_settings_spotifyClientIdConfirmation = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.lbl_settings_spotifyClientIdConfirmation.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_settings_spotifyClientIdConfirmation.setObjectName("lbl_settings_spotifyClientIdConfirmation")
        self.gridLayout_13.addWidget(self.lbl_settings_spotifyClientIdConfirmation, 4, 3, 1, 1)
        self.lbl_settings_apiKeySpotifyClientSpecial = QtWidgets.QLabel(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(12)
        self.lbl_settings_apiKeySpotifyClientSpecial.setFont(font)
        self.lbl_settings_apiKeySpotifyClientSpecial.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_settings_apiKeySpotifyClientSpecial.setObjectName("lbl_settings_apiKeySpotifyClientSpecial")
        self.gridLayout_13.addWidget(self.lbl_settings_apiKeySpotifyClientSpecial, 5, 0, 1, 1)
        self.btn_settings_spotifyClientSpecialKeyUpdate = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        self.btn_settings_spotifyClientSpecialKeyUpdate.setFont(font)
        self.btn_settings_spotifyClientSpecialKeyUpdate.setObjectName("btn_settings_spotifyClientSpecialKeyUpdate")
        self.gridLayout_13.addWidget(self.btn_settings_spotifyClientSpecialKeyUpdate, 5, 3, 1, 1)
        self.lineEdit_settings_spotifyClientSpecialId = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        self.lineEdit_settings_spotifyClientSpecialId.setFont(font)
        self.lineEdit_settings_spotifyClientSpecialId.setObjectName("lineEdit_settings_spotifyClientSpecialId")
        self.gridLayout_13.addWidget(self.lineEdit_settings_spotifyClientSpecialId, 5, 1, 1, 1)
        self.btn_settings_youtubeKeyShow = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        self.btn_settings_youtubeKeyShow.setFont(font)
        self.btn_settings_youtubeKeyShow.setCheckable(False)
        self.btn_settings_youtubeKeyShow.setObjectName("btn_settings_youtubeKeyShow")
        self.gridLayout_13.addWidget(self.btn_settings_youtubeKeyShow, 1, 2, 1, 1)
        self.lineEdit_settings_youtube = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        self.lineEdit_settings_youtube.setFont(font)
        self.lineEdit_settings_youtube.setObjectName("lineEdit_settings_youtube")
        self.gridLayout_13.addWidget(self.lineEdit_settings_youtube, 1, 1, 1, 1)
        self.btn_settings_spotifyClientIDKeyUpdate = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        self.btn_settings_spotifyClientIDKeyUpdate.setFont(font)
        self.btn_settings_spotifyClientIDKeyUpdate.setObjectName("btn_settings_spotifyClientIDKeyUpdate")
        self.gridLayout_13.addWidget(self.btn_settings_spotifyClientIDKeyUpdate, 3, 3, 1, 1)
        self.btn_settings_spotifyKeyShowClientID = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        self.btn_settings_spotifyKeyShowClientID.setFont(font)
        self.btn_settings_spotifyKeyShowClientID.setObjectName("btn_settings_spotifyKeyShowClientID")
        self.gridLayout_13.addWidget(self.btn_settings_spotifyKeyShowClientID, 3, 2, 1, 1)
        self.lbl_settings_apiKeyYoutube = QtWidgets.QLabel(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(12)
        self.lbl_settings_apiKeyYoutube.setFont(font)
        self.lbl_settings_apiKeyYoutube.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_settings_apiKeyYoutube.setObjectName("lbl_settings_apiKeyYoutube")
        self.gridLayout_13.addWidget(self.lbl_settings_apiKeyYoutube, 1, 0, 1, 1)
        self.lbl_settings_apiKeySpotifyClientID = QtWidgets.QLabel(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(12)
        self.lbl_settings_apiKeySpotifyClientID.setFont(font)
        self.lbl_settings_apiKeySpotifyClientID.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_settings_apiKeySpotifyClientID.setObjectName("lbl_settings_apiKeySpotifyClientID")
        self.gridLayout_13.addWidget(self.lbl_settings_apiKeySpotifyClientID, 3, 0, 1, 1)
        self.btn_settings_youtubeKeyUpdate = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        self.btn_settings_youtubeKeyUpdate.setFont(font)
        self.btn_settings_youtubeKeyUpdate.setObjectName("btn_settings_youtubeKeyUpdate")
        self.gridLayout_13.addWidget(self.btn_settings_youtubeKeyUpdate, 1, 3, 1, 1)
        self.lineEdit_settings_spotifyClientId = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        self.lineEdit_settings_spotifyClientId.setFont(font)
        self.lineEdit_settings_spotifyClientId.setObjectName("lineEdit_settings_spotifyClientId")
        self.gridLayout_13.addWidget(self.lineEdit_settings_spotifyClientId, 3, 1, 1, 1)
        self.lbl_settings_youtubeInfo = QtWidgets.QLabel(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lbl_settings_youtubeInfo.setFont(font)
        self.lbl_settings_youtubeInfo.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_settings_youtubeInfo.setObjectName("lbl_settings_youtubeInfo")
        self.gridLayout_13.addWidget(self.lbl_settings_youtubeInfo, 0, 1, 1, 1)
        self.btn_settings_spotifyKeyShowClientSpecial = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        self.btn_settings_spotifyKeyShowClientSpecial.setFont(font)
        self.btn_settings_spotifyKeyShowClientSpecial.setObjectName("btn_settings_spotifyKeyShowClientSpecial")
        self.gridLayout_13.addWidget(self.btn_settings_spotifyKeyShowClientSpecial, 5, 2, 1, 1)
        self.lbl_settings_spotifyInfo = QtWidgets.QLabel(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lbl_settings_spotifyInfo.setFont(font)
        self.lbl_settings_spotifyInfo.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_settings_spotifyInfo.setObjectName("lbl_settings_spotifyInfo")
        self.gridLayout_13.addWidget(self.lbl_settings_spotifyInfo, 2, 1, 1, 1)
        self.lbl_settings_spotifyClientSpecialConfirmation = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.lbl_settings_spotifyClientSpecialConfirmation.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_settings_spotifyClientSpecialConfirmation.setObjectName("lbl_settings_spotifyClientSpecialConfirmation")
        self.gridLayout_13.addWidget(self.lbl_settings_spotifyClientSpecialConfirmation, 6, 3, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_13, 1, 0, 1, 1)
        self.lbl_settings_directory_paths = QtWidgets.QLabel(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_settings_directory_paths.setFont(font)
        self.lbl_settings_directory_paths.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_settings_directory_paths.setObjectName("lbl_settings_directory_paths")
        self.gridLayout_7.addWidget(self.lbl_settings_directory_paths, 2, 0, 1, 1)
        self.gridLayout_14 = QtWidgets.QGridLayout()
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.btn_settings_directory_music_show = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.btn_settings_directory_music_show.setObjectName("btn_settings_directory_music_show")
        self.gridLayout_14.addWidget(self.btn_settings_directory_music_show, 1, 2, 1, 1)
        self.lineEdit_settings_directory_youtube = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.lineEdit_settings_directory_youtube.setObjectName("lineEdit_settings_directory_youtube")
        self.gridLayout_14.addWidget(self.lineEdit_settings_directory_youtube, 2, 2, 1, 5)
        self.radioButton_settings_directory_music_windows = QtWidgets.QRadioButton(self.gridLayoutWidget_4)
        self.radioButton_settings_directory_music_windows.setAutoExclusive(False)
        self.radioButton_settings_directory_music_windows.setObjectName("radioButton_settings_directory_music_windows")
        self.gridLayout_14.addWidget(self.radioButton_settings_directory_music_windows, 1, 4, 1, 1)
        self.lbl_settings_directory_music = QtWidgets.QLabel(self.gridLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_settings_directory_music.sizePolicy().hasHeightForWidth())
        self.lbl_settings_directory_music.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_settings_directory_music.setFont(font)
        self.lbl_settings_directory_music.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_settings_directory_music.setWordWrap(False)
        self.lbl_settings_directory_music.setObjectName("lbl_settings_directory_music")
        self.gridLayout_14.addWidget(self.lbl_settings_directory_music, 0, 1, 1, 1)
        self.btn_settings_directory_music_update = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.btn_settings_directory_music_update.setObjectName("btn_settings_directory_music_update")
        self.gridLayout_14.addWidget(self.btn_settings_directory_music_update, 1, 3, 1, 1)
        self.lbl_settings_directory_youtube = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.lbl_settings_directory_youtube.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_settings_directory_youtube.setObjectName("lbl_settings_directory_youtube")
        self.gridLayout_14.addWidget(self.lbl_settings_directory_youtube, 2, 1, 1, 1)
        self.btn_settings_directory_music_operating_system = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.btn_settings_directory_music_operating_system.setObjectName("btn_settings_directory_music_operating_system")
        self.gridLayout_14.addWidget(self.btn_settings_directory_music_operating_system, 1, 6, 1, 1)
        self.radioButton_settings_directory_youtube_windows = QtWidgets.QRadioButton(self.gridLayoutWidget_4)
        self.radioButton_settings_directory_youtube_windows.setAutoExclusive(False)
        self.radioButton_settings_directory_youtube_windows.setObjectName("radioButton_settings_directory_youtube_windows")
        self.gridLayout_14.addWidget(self.radioButton_settings_directory_youtube_windows, 3, 4, 1, 1)
        self.lineEdit_settings_directory_music = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.lineEdit_settings_directory_music.setObjectName("lineEdit_settings_directory_music")
        self.gridLayout_14.addWidget(self.lineEdit_settings_directory_music, 0, 2, 1, 5)
        self.btn_settings_directory_youtube_show = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.btn_settings_directory_youtube_show.setObjectName("btn_settings_directory_youtube_show")
        self.gridLayout_14.addWidget(self.btn_settings_directory_youtube_show, 3, 2, 1, 1)
        self.btn_settings_directory_youtube_update = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.btn_settings_directory_youtube_update.setObjectName("btn_settings_directory_youtube_update")
        self.gridLayout_14.addWidget(self.btn_settings_directory_youtube_update, 3, 3, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_14.addItem(spacerItem8, 4, 3, 1, 1)
        self.btn_settings_directory_youtube_operating_system = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.btn_settings_directory_youtube_operating_system.setObjectName("btn_settings_directory_youtube_operating_system")
        self.gridLayout_14.addWidget(self.btn_settings_directory_youtube_operating_system, 3, 6, 1, 1)
        self.radioButton_settings_directory_youtube_linux = QtWidgets.QRadioButton(self.gridLayoutWidget_4)
        self.radioButton_settings_directory_youtube_linux.setChecked(True)
        self.radioButton_settings_directory_youtube_linux.setAutoExclusive(False)
        self.radioButton_settings_directory_youtube_linux.setObjectName("radioButton_settings_directory_youtube_linux")
        self.gridLayout_14.addWidget(self.radioButton_settings_directory_youtube_linux, 3, 5, 1, 1)
        self.radioButton_settings_directory_music_linux = QtWidgets.QRadioButton(self.gridLayoutWidget_4)
        self.radioButton_settings_directory_music_linux.setChecked(True)
        self.radioButton_settings_directory_music_linux.setAutoExclusive(False)
        self.radioButton_settings_directory_music_linux.setObjectName("radioButton_settings_directory_music_linux")
        self.gridLayout_14.addWidget(self.radioButton_settings_directory_music_linux, 1, 5, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_14, 3, 0, 1, 1)
        self.tabWidget_main.addTab(self.tab_Settings, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 803, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.filemenu_actionExit = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        self.filemenu_actionExit.setFont(font)
        self.filemenu_actionExit.setObjectName("filemenu_actionExit")
        self.menuFile.addAction(self.filemenu_actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget_main.setCurrentIndex(0)
        self.comboBox_musicDl_artistInDB.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Music Downloader"))
        self.btn_youtubeChannel_addRemove.setText(_translate("MainWindow", "Add or Remove Channel from DB"))
        self.btn_youtubeChannel_updateList.setText(_translate("MainWindow", "Get Channels"))
        self.btn_youtubeChannel_download.setText(_translate("MainWindow", "Download"))
        self.btn_youtubeChannel_removeFromList.setText(_translate("MainWindow", "Remove from List"))
        self.tabWidget_main.setTabText(self.tabWidget_main.indexOf(self.tab_youtubeDownloader), _translate("MainWindow", "Youtube Channel"))
        self.lbl_musicDl_listWidgetInfo.setText(_translate("MainWindow", "*Albums in Bold Indicate they have already been Downloaded*"))
        self.btn_musicDl_downloadAlbums.setText(_translate("MainWindow", "Download"))
        self.lbl_musicDl_artistNameInfo.setText(_translate("MainWindow", "Enter the Artist\'s Name to get the ID:"))
        self.lbl_musicDl_artistIdInfo.setText(_translate("MainWindow", "Enter the Artists spotify ID to Search Albums:"))
        self.lbl_musicDl_artistComboBoxInfo.setText(_translate("MainWindow", "Get Artists in the Database:"))
        self.checkBox_musicDl_enableComboBox.setText(_translate("MainWindow", "Enable Combo Box"))
        self.lbl_musicDl_enableComboBox.setText(_translate("MainWindow", "Check To Get Artists From Database:"))
        self.btn_musicDl_populateLists.setText(_translate("MainWindow", "Get Albums"))
        self.btn_musicDl_toDownload.setText(_translate("MainWindow", "-->"))
        self.lbl_musicDL_transferInfo.setText(_translate("MainWindow", "Send Album"))
        self.btn_musicDl_toFound.setText(_translate("MainWindow", "<--"))
        self.btn_musicDl_lookupAlbum.setText(_translate("MainWindow", "<-- Lookup selected"))
        self.lbl_musicDl_albumsFound.setText(_translate("MainWindow", "Albums Found"))
        self.lbl_musicDl_albumsToDownload.setText(_translate("MainWindow", "Albums to Download"))
        self.lbl_musicDl_downloaded.setText(_translate("MainWindow", "Downloaded: 100%"))
        self.tabWidget_main.setTabText(self.tabWidget_main.indexOf(self.tab_musicDownloader), _translate("MainWindow", "Music Downloader"))
        self.btn_albumCorrection_updateSong.setText(_translate("MainWindow", "Update Song"))
        self.lbl_albumCorrection_song_spotify_id.setText(_translate("MainWindow", "Song_Spotify_Id"))
        self.lbl_albumCorrection_songYoutubeId.setText(_translate("MainWindow", "Song_Youtube_Id"))
        self.lbl_albumCorrection_songLbl.setText(_translate("MainWindow", "Song:"))
        self.lbl_albumCorrection_albumLbl.setText(_translate("MainWindow", "Album:"))
        self.lbl_albumCorrection_artistLbl.setText(_translate("MainWindow", "Artist:"))
        self.lbl_albumCorrection_song_name.setText(_translate("MainWindow", "Song_Name"))
        self.lbl_AlbumCorrection_completionText.setText(_translate("MainWindow", "----------"))
        self.btn_albumCorrection_youtubeWebSearch.setText(_translate("MainWindow", "Search Youtube for the Song"))
        self.tabWidget_main.setTabText(self.tabWidget_main.indexOf(self.tab_album_correction), _translate("MainWindow", "Album Correction"))
        self.lbl_settings_apiInfo.setText(_translate("MainWindow", "Api Keys"))
        self.lbl_settings_youtubeConfirmation.setText(_translate("MainWindow", "----------"))
        self.lbl_settings_spotifyClientIdConfirmation.setText(_translate("MainWindow", "----------"))
        self.lbl_settings_apiKeySpotifyClientSpecial.setText(_translate("MainWindow", "Client Special:"))
        self.btn_settings_spotifyClientSpecialKeyUpdate.setText(_translate("MainWindow", "Update Key"))
        self.btn_settings_youtubeKeyShow.setText(_translate("MainWindow", "Show Key"))
        self.btn_settings_spotifyClientIDKeyUpdate.setText(_translate("MainWindow", "Update Key"))
        self.btn_settings_spotifyKeyShowClientID.setText(_translate("MainWindow", "Show Key"))
        self.lbl_settings_apiKeyYoutube.setText(_translate("MainWindow", "Youtube:"))
        self.lbl_settings_apiKeySpotifyClientID.setText(_translate("MainWindow", "Client ID:"))
        self.btn_settings_youtubeKeyUpdate.setText(_translate("MainWindow", "Update Key"))
        self.lbl_settings_youtubeInfo.setText(_translate("MainWindow", "Youtube"))
        self.btn_settings_spotifyKeyShowClientSpecial.setText(_translate("MainWindow", "Show Key"))
        self.lbl_settings_spotifyInfo.setText(_translate("MainWindow", "Spotify"))
        self.lbl_settings_spotifyClientSpecialConfirmation.setText(_translate("MainWindow", "----------"))
        self.lbl_settings_directory_paths.setText(_translate("MainWindow", "Directories"))
        self.btn_settings_directory_music_show.setText(_translate("MainWindow", "Show"))
        self.radioButton_settings_directory_music_windows.setText(_translate("MainWindow", "Wi&ndows"))
        self.lbl_settings_directory_music.setText(_translate("MainWindow", "Music:"))
        self.btn_settings_directory_music_update.setText(_translate("MainWindow", "Update"))
        self.lbl_settings_directory_youtube.setText(_translate("MainWindow", "Youtube:"))
        self.btn_settings_directory_music_operating_system.setText(_translate("MainWindow", "Set System"))
        self.radioButton_settings_directory_youtube_windows.setText(_translate("MainWindow", "Windows"))
        self.btn_settings_directory_youtube_show.setText(_translate("MainWindow", "Show"))
        self.btn_settings_directory_youtube_update.setText(_translate("MainWindow", "Update"))
        self.btn_settings_directory_youtube_operating_system.setText(_translate("MainWindow", "Set System"))
        self.radioButton_settings_directory_youtube_linux.setText(_translate("MainWindow", "Lin&ux"))
        self.radioButton_settings_directory_music_linux.setText(_translate("MainWindow", "&Linux"))
        self.tabWidget_main.setTabText(self.tabWidget_main.indexOf(self.tab_Settings), _translate("MainWindow", "Settings"))
        self.menuFile.setTitle(_translate("MainWindow", "F&ile"))
        self.filemenu_actionExit.setText(_translate("MainWindow", "&Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

